<?php 

/**
 * Certificates Custom Fields
 */

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_5612fe80f3bfb',
	'title' => 'Certificates',
	'fields' => array (
		array (
			'key' => 'field_5618388c2ff51',
			'label' => 'Participant\'s Name',
			'name' => 'name',
			'type' => 'text',
			'instructions' => 'Full name as it appears in the passport.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'participant_name',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5612fe8fe2a39',
			'label' => 'Passport/ID',
			'name' => 'passport_id',
			'type' => 'text',
			'instructions' => 'Participant\'s Passport No. or National ID',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'passport_id',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'id or passport number',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5612fef2fdc33',
			'label' => 'Place of Birth',
			'name' => 'place_of_birth',
			'type' => 'text',
			'instructions' => 'Participant\'s country of birth (not nationality).',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'nationality',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'nationality',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5619ac69b2aab',
			'label' => 'Date of Birth',
			'name' => 'date_of_birth',
			'type' => 'date_picker',
			'instructions' => 'Participant\'s date of birth as seen in passport or id.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'nationality',
				'id' => '',
			),
			'display_format' => 'F j, Y',
			'return_format' => 'F j, Y',
			'first_day' => 1,
		),
		array (
			'key' => 'field_5612ff11fdc34',
			'label' => 'Course',
			'name' => 'course',
			'type' => 'post_object',
			'instructions' => 'Select course taken.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'select_course',
				'id' => '',
			),
			'post_type' => array (
				0 => 'courses',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
		),
		array (
			'key' => 'field_56130060acfc8',
			'label' => 'Start Date',
			'name' => 'start_date',
			'type' => 'date_picker',
			'instructions' => 'Course start date.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'course-date',
				'id' => '',
			),
			'display_format' => 'F j, Y',
			'return_format' => 'F j, Y',
			'first_day' => 1,
		),
		array (
			'key' => 'field_56130098acfc9',
			'label' => 'End Date',
			'name' => 'end_date',
			'type' => 'date_picker',
			'instructions' => 'Course end date.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'course-date',
				'id' => '',
			),
			'display_format' => 'F j, Y',
			'return_format' => 'F j, Y',
			'first_day' => 1,
		),
		array (
			'key' => 'field_5613068549b90',
			'label' => 'Instructor',
			'name' => 'instructor',
			'type' => 'post_object',
			'instructions' => 'Choose instructor who gave this course',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'instructor-field',
				'id' => '',
			),
			'post_type' => array (
				0 => 'instructors',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
		),
		array (
			'key' => 'field_561d82af8c0a7',
			'label' => 'Place of Training',
			'name' => 'place_of_training',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5619b14370c01',
			'label' => 'Place of Issuance',
			'name' => 'place_of_issuance',
			'type' => 'text',
			'instructions' => 'Country this certificate was issued.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Panama',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5619b16e70c02',
			'label' => 'Date of Issuance',
			'name' => 'date_of_issuance',
			'type' => 'date_picker',
			'instructions' => 'Date this certificate was issued.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'F j, Y',
			'return_format' => 'F j, Y',
			'first_day' => 1,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'certificates',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;